name: "[Scheduled] Terraform Cleanup"

on:
  schedule:
    - cron: "0 6,18 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: unfor19/install-aws-cli-action@27d6061dae5d39e89be4d2246824f15e111a7e06
      - uses: hashicorp/setup-terraform@v3.1.2

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a78e788c51463a506fbaaec784bab37f73afb4e8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-2
          role-duration-seconds: 1800
          role-session-name: TerraformGithubAction

      - name: Set Terraform version
        working-directory: terraform/ephemeral
        id: set-terraform-version
        run: |
          TF_VERSION=$(cat .terraform-version)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_OUTPUT
      
      - name: Terraform Init
        working-directory: terraform/ephemeral
        run: |
          terraform init -input=false

      - name: Terraform Cleanup
        working-directory: terraform/ephemeral
        run: |
          terraform init
          terraform destroy -auto-approve -var "allowed_ip=${{ secrets.allowed_ip }}"

      
      
      
