name: "[Workflow] Pull Request"

on:
  push:
    branches: [main]

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: Output workflow variables
    outputs:
      path: ${{ steps.variables.outputs.path }}
    steps:
      - uses: actions/checkout@v4
  
      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: permanent-changes
        with:
          files: |
            permanent/**
      - name: Check changes to ephemeral infra
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: ephemeral-changes
        with:
          files: |
            ephemeral/**
      - name: Check changes to documentation
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: documentation-changes
        with:
          files: |
            **/*.md
      - name: Extract variables for workflow
        id: variables
        run: |
          if [[ ${{ steps.permanent-changes.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo permanent)" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.ephemeral-changes.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo ephemeral)" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.documentation-changes.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo documentation)" >> $GITHUB_OUTPUT
          else
            echo "path=$(echo all)" >> $GITHUB_OUTPUT
          fi
      - name: Show path
        env:
          SPECIFIC_PATH: ${{ steps.variables.outputs.path }}
        run: |
          echo "path: $SPECIFIC_PATH"

  update_documentation:
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.path == 'docs'
      
  terraform_plan_ephemeral:
    name: Terraform Plan Ephemeral
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: needs.workflow_variables.output.path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success'&&
      needs.workflow_variables.outputs.path == 'ephemeral'

  terraform_apply_ephemeral:
    name: Terraform Plan Ephemeral
    uses: ./.github/workflows/terraform_apply.yaml
    needs: 
      - workflow_variables
      - terraform_plan_ephemeral
    with:
      directory: needs.workflow_variables.output.specific_path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success'&&
      needs.workflow_variables.outputs.path == 'ephemeral'
      
  terraform_plan_permanent:
    name: Terraform Plan Permanent
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: needs.workflow_variables.output.path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.path == 'permanent'
      
  terraform_apply_permanent:
    name: Terraform Plan Permanent
    uses: ./.github/workflows/terraform_apply.yaml
    needs: 
      - workflow_variables
      - terraform_plan_permanent
    with:
      directory: needs.workflow_variables.output.specific_path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.path == 'permanent'
      

      