name: "[Workflow] Path to Live"

on:
  push:
    branches: 
      - main

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: Output workflow variables
    outputs:
      specific_path: ${{ steps.variables.outputs.path }}
      plan_or_apply: ${{ steps.terraform_plan_or_apply.outputs.path}}
    steps:
      - uses: actions/checkout@v4

      - name: Show filesystem directory
        run: |
          echo "Directory: $GITHUB_WORKSPACE"

      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@v44
        id: terraform-changes
        with:
          files: |
            terraform/**
      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@v44
        id: permanent-changes
        with:
          files: |
            terraform/permanent/**
      - name: Check changes to ephemeral infra
        uses: tj-actions/changed-files@v44
        id: ephemeral-changes
        with:
          files: |
            permanent/ephemeral/**
      - name: Check changes to documentation
        uses: tj-actions/changed-files@v44
        id: documentation-changes
        with:
          files: |
            **/*.md
      - name: Extract variables for workflow
        id: variables
        run: |
          if [[ ${{ steps.terraform-changes.outputs.any_changed }} = "true" ]]
          then
            if [[ ${{ steps.permanent-changes.outputs.only_changed }} = "true" ]]
            then
              echo "path=$(echo permanent)" >> $GITHUB_OUTPUT
            elif [[ ${{ steps.ephemeral-changes.outputs.only_changed }} = "true" ]]
            then
              echo "path=$(echo ephemeral)" >> $GITHUB_OUTPUT
            else
              echo "path=$(echo terraform)" >> $GITHUB_OUTPUT
            fi
          elif [[ ${{ steps.documentation-changes.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo docs)" >> $GITHUB_OUTPUT
          else
            echo "path=$(echo all)" >> $GITHUB_OUTPUT
          fi  
      - name: Show results
        env:
          SPECIFIC_PATH: ${{ steps.variables.outputs.path }}
        run: |
          echo "path: $SPECIFIC_PATH"

      - name: Plan or Apply
        id: terraform_plan_or_apply
        run: | 
          if [[ ${{ github.ref == 'refs/heads/main' }} ]];
          then
            echo "path=$(echo apply)" >> $GITHUB_OUTPUT
          else
            echo "path=$(echo plan)" >> $GITHUB_OUTPUT
          fi

  update_documentation:
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
    steps:
      - name: Only update docs
        run: echo "Only updating documentation"
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.specific_path == 'docs' || 
      needs.workflow_variables.outputs.specific_path == 'all'

  terraform_apply_ephemeral:
    name: Terraform Apply Ephemeral
    uses: ./.github/workflows/terraform.yaml
    needs: 
      - workflow_variables
    with:
      directory: 'ephemeral'
      plan_or_apply: ${{ needs.workflow_variables.outputs.plan_or_apply }}
    secrets: inherit
    if: |
      needs.workflow_variables.result.success == 'success' &&
      needs.workflow_variables.outputs.plan_or_apply == 'apply' &&
      (needs.workflow_variables.outputs.specific_path == 'ephemeral' ||
      needs.workflow_variables.outputs.specific_path == 'terraform')
  terraform_apply_permanent:
    name: Terraform Apply Permanent
    uses: ./.github/workflows/terraform.yaml
    needs: 
      - workflow_variables
    with:
      directory: 'permanent'
      plan_or_apply: ${{ needs.workflow_variables.outputs.plan_or_apply }}
    secrets: inherit
    if: |
      needs.workflow_variables.result.success == 'success' &&
      needs.workflow_variables.outputs.plan_or_apply == 'apply' &&
      (needs.workflow_variables.outputs.specific_path == 'permanent' ||
      needs.workflow_variables.outputs.specific_path == 'terraform')
      