name: "[Workflow] Pull Request"

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: Output workflow variables
    outputs:
      documentation: ${{ steps.variables.outputs.docs }}
      ephemeral_terraform: ${{ steps.variables.outputs.ephemeral }}
      permanent_terraform: ${{ steps.variables.outputs.permanent }}
    steps:
      - uses: actions/checkout@v4

      - name: Show filesystem directory
        run: |
          echo "Directory: $GITHUB_WORKSPACE"
  
      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: permanent-changes
        with:
          files: |
            permanent/**
      - name: Check changes to ephemeral infra
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: ephemeral-changes
        with:
          files: |
            ephemeral/**
      - name: Check changes to documentation
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: documentation-changes
        with:
          files: |
            **/*.md
      - name: Extract variables for workflow
        id: variables
        run: |
          if [[ ${{ steps.permanent-changes.outputs.any_changed }} = "true" ]]
          then
            echo "permanent_terraform=$(echo changed)" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.ephemeral-changes.outputs.any_changed }} = "true" ]]
          then
            echo "ephemeral_terraform=$(echo changed)" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.documentation-changes.outputs.only_changed }} = "true" ]]
          then
            echo "documentation=$(echo changed)" >> $GITHUB_OUTPUT
          fi
      - name: Show results
        env:
          PERMANENT: ${{ steps.variables.outputs.permanent }}
          EPHEMERAL: ${{ steps.variables.outputs.ephemeral }}
          DOCS: ${{ steps.variables.outputs.docs }}
        run: |
          echo "path: $SPECIFIC_PATH"

  update_documentation:
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
    steps:
      - name: Only update docs
        run: echo "Only updating documentation"
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.documentation == 'changed'

  terraform_plan_ephemeral:
    name: Terraform Plan Ephemeral
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: needs.workflow_variables.output.specific_path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.ephemeral_terraform == 'ephemeral'
      
  terraform_plan_permanent:
    name: Terraform Plan Permanent
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: needs.workflow_variables.output.specific_path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.permanent_terraform == 'permanent'
      