name: "[Workflow] Pull Request"

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: Output workflow variables
    outputs:
      docs: ${{ steps.variables.outputs.documentation }}
      ephemeral: ${{ steps.variables.outputs.ephemeral_terraform }}
      permanent: ${{ steps.variables.outputs.permanent_terraform }}
    steps:
      - uses: actions/checkout@v4
  
      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: permanent-changes
        with:
          files: |
            permanent/**
      - name: Check changes to ephemeral infra
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: ephemeral-changes
        with:
          files: |
            ephemeral/**
      - name: Check changes to documentation
        uses: tj-actions/changed-files@41ce994be96a740b53ae11ecbf86d1619a7bd640
        id: documentation-changes
        with:
          files: |
            **/*.md
      - name: Extract variables for workflow
        id: variables
        run: |
          if [[ ${{ steps.permanent-changes.outputs.any_changed }} = "true" ]]
          then
            echo "permanent_terraform=changed" >> $GITHUB_ENV
          elif [[ ${{ steps.ephemeral-changes.outputs.any_changed }} = "true" ]]
          then
            echo "ephemeral_terraform=changed" >> $GITHUB_ENV
          elif [[ ${{ steps.documentation-changes.outputs.only_changed }} = "true" ]]
          then
            echo "documentation=changed" >> $GITHUB_ENV
          fi
      - name: Show results
        run: |
          echo "PERMANENT: $permanent_terraform"
          echo "EPHEMERAL: $ephemeral_terraform"
          echo "DOCS: $documentation"
          echo "var output: ${{ steps.variables.outputs.permanent }}"

  update_documentation:
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
    steps:
      - name: Only update docs
        run: echo "Only updating documentation"
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.docs == 'changed'

  terraform_plan_ephemeral:
    name: Terraform Plan Ephemeral
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: ephemeral
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.ephemeral == 'changed'
      
  terraform_plan_permanent:
    name: Terraform Plan Permanent
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: permanent
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.permanent == 'changed'
      