name: "[Workflow] Pull Request"

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: Output workflow variables
    outputs:
      specific_path: ${{ steps.variables.outputs.path }}
    steps:
      - uses: actions/checkout@v4

      - name: Show filesystem directory
        run: |
          echo "Directory: $GITHUB_WORKSPACE"

      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@v44
        id: terraform-changes
        with:
          files: |
            terraform/**

      - name: Check changes to permanent infra
        uses: tj-actions/changed-files@v44
        id: permanent-changes
        with:
          files: |
            terraform/permanent/**
      - name: Check changes to ephemeral infra
        uses: tj-actions/changed-files@v44
        id: ephemeral-changes
        with:
          files: |
            permanent/ephemeral/**
      - name: Check changes to documentation
        uses: tj-actions/changed-files@v44
        id: documentation-changes
        with:
          files: |
            **/*.md
      - name: Extract variables for workflow
        id: variables
        run: |
          if [[ ${{ steps.terraform-changes.outputs.only_changed }} = "true" ]]
          then
            if [[ ${{ steps.permanent-changes.outputs.only_changed }} = "true" ]]
            then
              echo "path=$(echo permanent)" >> $GITHUB_OUTPUT
            elif [[ ${{ steps.ephemeral-changes.outputs.only_changed }} = "true" ]]
            then
              echo "path=$(echo ephemeral)" >> $GITHUB_OUTPUT
            else
              echo "path=$(echo terraform)" >> $GITHUB_OUTPUT
            fi
          elif [[ ${{ steps.documentation-changes.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo docs)" >> $GITHUB_OUTPUT
          else
            echo "path=$(echo all)" >> $GITHUB_OUTPUT
          fi  
      - name: Show results
        env:
          SPECIFIC_PATH: ${{ steps.variables.outputs.path }}
        run: |
          echo "path: $SPECIFIC_PATH"

  update_documentation:
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
    steps:
      - name: Only update docs
        run: echo "Only updating documentation"
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.specific_path == 'docs' || 
      needs.workflow_variables.outputs.specific_path == 'all'

  terraform_plan_ephemeral:
    name: Terraform Plan Ephemeral
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: needs.workflow_variables.output.specific_path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.specific_path == 'ephemeral'
      
  terraform_plan_permanent:
    name: Terraform Plan Permanent
    uses: ./.github/workflows/terraform_plan.yaml
    needs: 
      - workflow_variables
    with:
      directory: needs.workflow_variables.output.specific_path
    secrets: inherit
    if: |
      needs.workflow_variables.result == 'success' &&
      needs.workflow_variables.outputs.specific_path == 'permanent'
      