name: "[Workflow] Terraform Apply"

on:
  push:
    branches: [main]

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: unfor19/install-aws-cli-action@27d6061dae5d39e89be4d2246824f15e111a7e06
      - uses: hashicorp/setup-terraform@1f0219f06bc83460a00897ce23371e4a3325db85

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a78e788c51463a506fbaaec784bab37f73afb4e8 # pin@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-2
          role-duration-seconds: 1800
          role-session-name: TerraformGithubAction


      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -input=false -lock-timeout=5m

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve