name: "[Workflow] Terraform Plan"

defaults:
  run:
    shell: bash

on: 
  workflow_call:
    inputs:
      directory:
        description: 'Terraform directory'
        required: true
        type: string


jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: unfor19/install-aws-cli-action@27d6061dae5d39e89be4d2246824f15e111a7e06
      - uses: hashicorp/setup-terraform@1f0219f06bc83460a00897ce23371e4a3325db85

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a78e788c51463a506fbaaec784bab37f73afb4e8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-2
          role-duration-seconds: 1800
          role-session-name: TerraformGithubAction

      - name: Terraform init
        run: terraform init -input=false
        working-directory: ./${{ inputs.directory }}

      - name: Terraform plan
        run: terraform plan -input=false -lock-timeout=5m
        working-directory: ./${{ inputs.directory }}
